#!/bin/bash

# Automatic settinger ADB v.1.0
# Author - Findlee
# E-Mail - thefindlee@gmail.com
# Profile on 4pda.ru - http://4pda.ru/forum/index.php?showuser=1498763
# Special for sony-developers.ru
# Thank user BPaul(paul-xxx) for help

setterm -bold 
tput setaf 1 
if [[ ! "$UID" -eq 0 ]]
then
echo "You not have root permissions. Use sudo."
tput sgr0
sleep 2
exit $?
fi

while :
do

setterm -bold 
tput setaf 1 
clear
echo "============================================================="
echo "Automatic Settinger ADB v.1.0 by Findlee"
echo "============================================================="
tput sgr0

echo "
1)All Android Devices
2)Exit
"
read -p "Select option: " opt
echo ""
case $opt in
1)
setterm -bold 
tput setaf 1
echo "Installation Android IDvendors to System"
read -s -n1 -p "Press any key to continue" keypress
echo -e "\nDeleting old .rules , if have"
rm -f /etc/udev/rules.d/*-android.*
echo "Creating new .rules file"
cp 51-android.rules /etc/udev/rules.d/51-android.rules
echo "Setting permissions"
chmod a+r /etc/udev/rules.d/51-android.rules
echo "Restarting udev service"
service udev restart
echo "Stopping adb server"
adb kill-server
echo "Starting adb server"
adb start-server
echo "Checking adb devices"
adb devices
echo "Installation Completed"
tput sgr0
read -s -n1 -p "Press any key to continue" keypress
;;

2)exit
;;
esac
done
